base_url: "http://www.deadchannel.ru/"
title: Dead Channel
description: Сайт о тёмной сцене.
language: ru_RU
disqus_id: deadchannel
comment_labels: [blog, podcast, video]

flattr_name: umonkey
flattr_labels: [blog, video, podcast]

buttons:
  labels: [podcast, interviews, knowledge, concerts]
  items:
  - type: vk_share
    image: /files/btn_vkontakte.png
    title: Поделиться ВКонтакте
    link: "http://vkontakte.ru/share.php?url=%(url)s"
  - type: flattr
    image: /files/btn_flattr.png
    title: Поддержать материально
    link: "https://flattr.com/submit/auto?user_id=umonkey&amp;url=%(url)s&amp;title=%(title)s&amp;description=%(summary)s&amp;language=ru_RU&amp;tags=%(labels)s&amp;category=%(category)s"

authors:
- name: umonkey
  fullname: Хекс
  email: hex@umonkey.net
  profile: "https://profiles.google.com/justin.forest/about"
- name: jeteir
  email: jeteir@gmail.com
- name: under_deck
  fullname: "Игорь (under_deck) Баранов"
  email: underdeck@mail.ru
  profile: "http://vk.com/under_deck"
- name: bolivar
  email: bolivar1977@rambler.ru
- name: C3-359
  fullname: Галина Алексеева
  email: c3-359@gmail.com
  profile: "https://plus.google.com/117421182472253280888/about"
- name: Lisa Mueller
  email: info@deadchannel.ru
  profile: "http://vk.com/deutschrockgirl"

labels:
- name: podcast
  title: подкасты
  link: /podcasts/
  rss_file: podcasts.xml
  rss_title: "Подкаст Dead Channel"
  rss_description: "Мысли и интервью на тему тёмной сцены."
- name: interviews
  title: интервью
  link: /interviews/
  rss_file: interviews.xml
  rss_title: "Интервью для Dead Channel"
  rss_description: "Интервью с деятелями тёмной сцены."
- name: articles
  title: статьи
  link: /articles/
  rss_file: articles.xml
  rss_title: "Статьи для Dead Channel"
  rss_description: "Статьи, написанные специально для Dead Channel."
- name: knowledge
  title: ликбез
  link: /knowledge/
  rss_file: knowledge.xml
  rss_title: "Ликбез от Dead Channel"
  rss_description: "Информационные статьи от Dead Channel."
- name: concerts
  title: отчёты
  link: /concerts/
  rss_file: concerts.xml
  rss_title: "Отчёты о концертах"
  rss_description: "Отчёты, написанные для Dead Channel."
- name: reviews
  title: рецензии
  link: /reviews/
